// NystromSpecCMITest.h automatically generated by bin/add_new_algorithm.pl
// in Wed Feb  7 12:10:39 2018.

//
// NystromSpecCMITest.h -- definition of the namespace "NystromSpecCMITest".
//
//    This file is part of the featsel program
//    Copyright (C) 2017  Author
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef NYSTROMSPECCMITEST_H_
#define NYSTROMSPECCMITEST_H_

#include "../../src/algorithms/NystromSpecCMI.h"
#include "../../src/functions/SubsetSum.h"
#include "../../src/functions/HammingDistance.h"

namespace NystromSpecCMITest
{
	
  bool it_should_sample_SpecCMI_Q_matrix ();

}

#endif /* NYSTROMSPECCMITEST_H_ */
