// CHCGA.h automatically generated by bin/add_new_algorithm.pl
// in Fri May  4 11:19:48 2018.

//
// CHCGA.h -- definition of the class "CHCGA".
//
//    This file is part of the featsel program
//    Copyright (C) 2018  Marcelo S. Reis, Gustavo Estrela
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef CHCGA_H_
#define CHCGA_H_

#include "../global.h"
#include "../Solver.h"
#include "../ElementSubset.h"


class CHCGA : public Solver
{

public:

  // Default constructor.
  //
  CHCGA ();

  // Default destructor.
  //
  virtual ~CHCGA ();

  // Run the algorithm, getting up to 'max_size_of_minima_list' minima.
  //
  void get_minima_list (unsigned int);

};

#endif /* CHCGA_H_ */
