// KRandomUChain.h automatically generated by bin/add_new_algorithm.pl
// in Wed Feb 14 12:58:52 2018.

//
// KRandomUChain.h -- definition of the class "KRandomUChain".
//
//    This file is part of the featsel program
//    Copyright (C) 2016  Marcelo S. Reis
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#ifndef KRANDOMUCHAIN_H_
#define KRANDOMUCHAIN_H_

#include "../global.h"
#include "../Solver.h"
#include "../ElementSubset.h"

#define K_REPETITIONS 8

class KRandomUChain : public Solver
{

private:

  // Stores the number of random chains that will be visited.
  //
  unsigned int k_repetitions;

public:

  // Default constructor.
  //
  KRandomUChain ();

  // Default destructor.
  //
  virtual ~KRandomUChain ();

  // Run the algorithm, getting up to 'max_size_of_minima_list' minima.
  //
  void get_minima_list (unsigned int);

};

#endif /* KRANDOMUCHAIN_H_ */
