// CFSTest.cpp automatically generated by bin/add_new_cost_function.pl
// in Fri Feb 17 16:34:55 2017.

//
// CFSTest.cpp -- implementation of the namespace "CFSTest".
//
//    This file is part of the featsel program
//    Copyright (C) 2016  Marcelo S. Reis
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

#include "CFSTest.h"

namespace CFSTest
{

  bool it_should_compute_the_correlation_based_feature_selection ()
  {
    // This instance is the same as "Test_3_1" in the Zoo data set, and applying
    // the CFS cost function onto it yields the following results:
    //
    // <111> : -0.611839
    // <011> : -0.575681
    // <110> : -0.548041
    // <101> : -0.543844
    // <001> : -0.511101
    // <100> : -0.463452
    // <010> : -0.359794
    // <000> : 3.40282e+38
    //
    ElementSet set (7, "input/cfs/Test_3_1.dat", 3);

    ElementSubset X ("X", &set);

    CFS c (&set);

    if (c.cost (&X) != FLT_MAX)      // X = 000
      return false;

    X.add_element (0);               // X = 100 
    if ((c.cost (&X) <= -0.463453) || (c.cost (&X) >= -0.463451))
      return false;

    X.add_element (1);               // X = 110
    if ((c.cost (&X) <= -0.548042) || (c.cost (&X) >= -0.548040))
      return false;

    X.add_element (2);               // X = 111
    if ((c.cost (&X) <= -0.611840) || (c.cost (&X) >= -0.611838))
      return false;

    X.remove_element (1);            // X = 101
    if ((c.cost (&X) <= -0.543845) || (c.cost (&X) >= -0.543843))
      return false;

    X.remove_element (0);            // X = 001
    if ((c.cost (&X) <= -0.511102) || (c.cost (&X) >= -0.511100))
      return false;
    
    X.add_element (1);               // X = 011
    if ((c.cost (&X) <= -0.575682) || (c.cost (&X) >= -0.575680))
      return false;

    X.remove_element (2);            // X = 010
    if ((c.cost (&X) <= -0.359795) || (c.cost (&X) >= -0.359793))
      return false;

    return true;
  }


  bool it_should_add_and_retrieve_the_elapsed_time ()
  {
    ElementSet set ("a_set", 1, 1);
    CFS c (&set);
    int t1 =    10,     // 0.00001 second
        t2 =   100,     // 0.0001 second
        t3 =   500,     // 0.0005 second
        t4 =  1000,     // 0.001 second
        t5 = 2000000,   // 2 seconds
        elapsed_time;

    // elapsed_time = 1500 microseconds
    c.add_elapsed_time (t3);
    c.add_elapsed_time (t4);
    elapsed_time =
    c.get_the_elapsed_time_of_the_calls_of_this_cost_function ();
    if (!(elapsed_time >= 0 && elapsed_time <= 3500)) // 2 ms precision
			return false;

    // elapsed_time = 1520 microseconds
    c.add_elapsed_time (t1);
    c.add_elapsed_time (t1);
    elapsed_time =
    c.get_the_elapsed_time_of_the_calls_of_this_cost_function ();
    if (!(elapsed_time >= 0 && elapsed_time <= 3520)) // 2 ms precision
      return false;

    // elapsed_time = 2120 microseconds
    c.add_elapsed_time (t3);
    c.add_elapsed_time (t2);
    elapsed_time =
    c.get_the_elapsed_time_of_the_calls_of_this_cost_function ();
    if (!(elapsed_time >= 120 && elapsed_time <= 4120)) // 2 ms precision
      return false;

    // elapsed_time = 2002120 microseconds
    c.add_elapsed_time (t5);
    elapsed_time =
    c.get_the_elapsed_time_of_the_calls_of_this_cost_function ();
    if (!(elapsed_time >= 2000120 && elapsed_time <= 2004120)) // 2ms precision
      return false;

    return true;
  }
  
  
  bool an_empty_set_should_have_cost_zero ()
  {
    ElementSet set ("set", "input/parsers/Test_XmlParserDriver_B.xml");
    ElementSubset O ("O", &set);
    CFS c (&set);

    if (c.cost (&O) != 0)
      return false;

    return true;
  }

} // end of namespace

