# CFS.pm automatically generated by bin/add_new_cost_function.pl
# in Fri Feb 17 16:34:55 2017.

#
# CFS.pm -- Perl module for instance generation of 
#              cfs cost function (dat file type). 
#
#    This file is part of the featsel program
#    Copyright (C) 2016  Marcelo S. Reis
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

package CFS;

use strict;


sub random_cfs_instance
{
  my ($size, $MAX_ELEMENT_VALUE, $INPUT_DIR, $id) = @_;

  my $file_name = sprintf "$INPUT_DIR/Test_%03d_%04d.dat", $size, $id;

  open (DAT, ">$file_name")
    or die "Cannot create '$file_name' file!\n";

  #
  # TODO: implement here the main code of your instance generator!
  #

  print DAT "0    1 2\n";
  print DAT "1    4 3\n";

  close (DAT);
}

# End of module
#
1;


